---
#
# Configure Kerberos client environemnt for a MongoD host
# 

- name: Install the latest version of krb5 client libs/tools
  yum: pkg=krb5-workstation state=installed

- name: Copy kerberos conf file and keytab to host machine ready to be used by MongoD
  copy: src=tmp/krb5.keytab dest=/etc/krb5.keytab owner=mongod group=mongod mode=0400
- copy: src=tmp/krb5.conf dest=/etc/krb5.conf owner=mongod group=mongod mode=0444

- name: Setup Kerberos environment variables for MongoD to pick up when it starts (including path of Kerberos client log file)
  lineinfile: dest=/etc/sysconfig/mongod regexp='' insertafter=EOF line='export KRB5_KTNAME=\"/etc/krb5.keytab\"' state=present
# Note: The addition below seems to remove the keytab file variable above, however /etc/krb5.keytab seems to be the default assumed location
- lineinfile: dest=/etc/sysconfig/mongod regexp='' insertafter=EOF line='export KRB5_TRACE=\"/var/log/mongodb/krbtrace.log\"' state=present

