---
#
# Install MongoDB database ensuring Huge Pages is disabled
# 

- name: Configure a script to disable huge pages and install NUMA control (which will be run by the mongod startup script)
  copy: src=os/disable-transparent-hugepages.j2 dest=/etc/init.d/disable-transparent-hugepages mode=a+x
- service: name=disable-transparent-hugepages enabled=yes state=started
- yum: name=numactl state=latest

- name: Install and configure MongoDB from the enterprise binaries repository
# TODO: Restore when MongoDB 3.4 is released to yum repos
# template: src=files/mongod/mongodb-enterprise.repo.j2 dest=/etc/yum.repos.d/mongodb-enterprise.repo
# TODO: REMOVE when 3.4 released >>>>>>>
  get_url: url=http://repo.mongodb.com/yum/redhat/7/mongodb-enterprise/3.3/x86_64/RPMS/mongodb-enterprise-unstable-server-3.3.11-1.el7.x86_64.rpm dest=/home/vagrant/mongodb-enterprise-unstable-server-3.3.11-1.el7.x86_64.rpm mode=0550
- get_url: url=http://repo.mongodb.com/yum/redhat/7/mongodb-enterprise/3.3/x86_64/RPMS/mongodb-enterprise-unstable-shell-3.3.11-1.el7.x86_64.rpm dest=/home/vagrant/mongodb-enterprise-unstable-shell-3.3.11-1.el7.x86_64.rpm mode=0550
- yum: pkg={{ item }} disable_gpg_check=yes state=present
  with_items:
    - net-snmp
    - cyrus-sasl
    - cyrus-sasl-plain
    - cyrus-sasl-gssapi
    - net-snmp-libs
- yum: name=/home/vagrant/{{ item }} state=present
  with_items:
    - mongodb-enterprise-unstable-server-3.3.11-1.el7.x86_64.rpm
    - mongodb-enterprise-unstable-shell-3.3.11-1.el7.x86_64.rpm
# TODO: <<<<<< END REMOVE
- copy: src=mongod/99-mongodb-nproc.conf.j2 dest=/etc/security/limits.d/99-mongodb-nproc.conf
# TODO: Restore when MongoDB 3.4 is released to yum repos
#- yum: name=mongodb-enterprise state=latest
- template: src=files/mongod/mongod.conf.j2 dest=/etc/mongod.conf owner=mongod group=mongod mode=u+rw

